---
- name: Ping network devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Test ICMP
      ansible.builtin.shell: 
        cmd: ping {{ inventory_hostname }}
      delegate_to: local_host
      register: ping_result

    - debug:
        var: ping_result
