---
- name: Ping network devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Test ICMP
      ansible.builtin.shell: 
        cmd: which ping
      register: ping_result

    - debug:
        var: ping_result
