---
- name: Ping network devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Test ICMP ping
      ansible.builtin.ping:
      register: ping_result
    - debug:
        var: ping_result

    # - name: Display ping results
    #   debug:
    #     msg: "{{ inventory_hostname }} is reachable"
    #   when: ping_result.ping is defined
