---
- name: Ping network devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Test ICMP
      ansible.builtin.command:
        cmd: ping {{ inventory_hostname }}
      register: ping_result

    - debug:
        var: ping_result
