---
- name: Configure domain name
  hosts: routers
  gather_facts: false
  tasks:
    - name: Send Command
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip interface brief
      register: show_command_output
    
    - name: Print show version
      ansible.builtin.debug:
        msg: "{{ show_command_output.stdout_lines[0] }}"
